---
title: "Taller de R en veRano  😎 ⛱️ 🏄  " 
author: "Psic Mariangeles Martinez"
format: 
  html:
    code-fold: false
    echo: false
    embed-resources: true
    author-title: "Autor:"
    toc: true                # Habilita la tabla de contenidos
    toc-title: "Índice de Contenidos"  # Título del índice
    toc-depth: 3             # Nivel de profundidad del índice (hasta h3)
    toc-location: left       # Ubicación del índice (izquierda)
    #include-before-body: logo.html # Incluye el logo antes del contenido
editor: visual
execute:
  warning: false
  message: false
footnotes-hover: true # muestra notas al pie
smooth-scroll: true # suaviza el scroll
code-copy: true            # Permite copiar el código desde el documento
include-in-header: HTML/header4.html
css: CSS/style.css
---

## ¿Qué es este taller? Objetivo

Es una aproximación a R. Tiene como objetivo introducirlxs a este lenguaje R y que puedan realizar manejo de datos y presentaciones de los mismos. El desafio es mandarse a jugar un poco y probar, probar y probar.

## Dinámica de los encuentros

Este taller va a ser semanal y se realizará los **días miércoles de 8.30h a 10h**. La intención es que vayamos entre todxs metiendole mano a R desde el primer encuentro y no que vean solamente una PPT. Por otro lado, en R hay que practicar, practicar y practicar. Es por esto que les voy a ir compartiendo actividades para que vayan resolviendo por fuera de este taller. El lugar de encuentro: el aula de la residencia.

**Fecha de inicio: 15/01/2025**

## Intención final de este taller

Automatización del BEM 🔥

## "Elementos" necesarios para el taller

-   Tener R y RStudio instalado, versión lo más actualizada posible.

-   Paciencia: usar R puede resultar un poco frustrante, como la vida adulta en general. Recomiendo fuerte amigarse con la paciencia y no tirar de entrada la toalla y volver shorando a nuestro gran y fiel amigo Excel. Cuesta identificar los errores y “saber que hacer”, es complejo, es un lenguaje nuevo, etc 🥹\
    Más allá de estos males, hay mucha pero mucha info de R en la web. Hay comunidades, foros, miles de tutoriales en youtube y CHATGPT obviamente.\

-   Bases de datos nominal y agrupada (pero esto no para el 1° encuentro)

¿Qué vamos a ver en este taller? Cronograma/temario

+------------+-----------------------------------------------------------------------------------------------------------------------------+
| Fecha      | Tema                                                                                                                        |
+============+=============================================================================================================================+
| 15/01/2025 | ¿Qué es R? Componentes. Creación de un proyecto. Instalación de paquetes y librerías. Objetos, vectores.                    |
|            |                                                                                                                             |
|            | [PPT](https://docs.google.com/presentation/d/1SshRu0vGfkVj3EqSczcW9uHolhf6ZZ8YpXfBgPY6hn8/edit#slide=id.g20f7af2584a_0_14)  |
+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 22/01/2025 | Librerías y paquetes                                                                                                        |
|            |                                                                                                                             |
|            | Carga de base de datos y exploración de la misma                                                                            |
|            |                                                                                                                             |
|            | Formatos de variables. Mutate                                                                                               |
|            |                                                                                                                             |
|            | Dplyer                                                                                                                      |
|            |                                                                                                                             |
|            | Estructura básica de ggplot                                                                                                 |
|            |                                                                                                                             |
|            | <https://www.datacamp.com/es/tutorial/r-packages-guide>                                                                     |
|            |                                                                                                                             |
|            | <https://rstudio-pubs-static.s3.amazonaws.com/838661_1c4330e8950a44e1a4b94f68d299b55f.html#gr%C3%A1fico-de-dispersi%C3%B3n> |
|            |                                                                                                                             |
|            | <https://r-charts.com/es/parte-todo/grafico-barras-apiladas-ggplot2/>                                                       |
|            |                                                                                                                             |
|            | <https://epirhandbook.com/es/index.es.html>                                                                                 |
|            |                                                                                                                             |
|            | <https://r-graph-gallery.com/>                                                                                              |
|            |                                                                                                                             |
|            | Colores:                                                                                                                    |
|            |                                                                                                                             |
|            | <https://htmlcolorcodes.com/es/>                                                                                            |
|            |                                                                                                                             |
|            | <https://r-charts.com/es/colores/>                                                                                          |
|            |                                                                                                                             |
|            | <https://colorbrewer2.org/#type=sequential&scheme=BuGn&n=3>                                                                 |
|            |                                                                                                                             |
|            | <https://coolors.co/>                                                                                                       |
|            |                                                                                                                             |
|            | <https://mycolor.space/>                                                                                                    |
+------------+-----------------------------------------------------------------------------------------------------------------------------+
| 29/01/2025 |                                                                                                                             |
+------------+-----------------------------------------------------------------------------------------------------------------------------+
|            |                                                                                                                             |
+------------+-----------------------------------------------------------------------------------------------------------------------------+
